# -*- coding: utf-8 -*-
"""DevOps and MLOps Course End Activity

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQE82EA7tD7aghAmYJjX6FFieueeXGzn
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pickle

df=pd.read_csv('230309_Bank_Note_Authentication_01/BankNote_Authentication.csv')

X=df.iloc[:,:-1]
y=df.iloc[:,-1]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

score

pickle_out = open("BankNote.pickle","wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()

classifier.predict([[2,3,4,1]])

